### ISSUE TITLE
#32 Bird view

### ISSUE THREAD

**Issue by darkokos** [darkokos/sok-project#32]
- [x] Create graph bird view on the main page. This view should display the miniature version of the entire graph, regardless of it's size
- [x] The view should have a viewport within it which captures the current position and dimensions of the main view. The view port should move/resize in sync with the change of the position and dimensions of the main view
- [ ] Pressing anywhere within the bird view should focus the viewport on the pressed location, as well as changing the main view position, accordingly

**Comment by teodord25** [comment]
bruh
